name: Upload Python Package
##############################################
# Create A Release to trigger a build       ##
# make sure your tag is Maj.Min.Build form  ##
##############################################
on:
  release:
    types: # This configuration does not affect the page_build event above
      - created
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Identifier'
        required: true
        default: 'a0.0.0v'
jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.release.target_commitish }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      id: ident
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        pip install . -v # install our package
        if [[ "${{ github.event.inputs.version }}" == "" ]]; then
          echo "DEPLOY VIA RELEASES!"
          echo "::set-output name=VERSION::${GITHUB_REF##*/}"
          echo "::set-output name=IS_RELEASE::true"
        else
          echo "DEPLOY VIA TEST BUTTON"
          echo "::set-output name=VERSION::${{ github.event.inputs.version }}"
          echo "::set-output name=IS_TEST::true"
        fi
    - name: Update Version
      run: |
        TAG=${{ steps.ident.outputs.VERSION }}
        rel-easy setver --version $TAG --sha1

    - name: TEST Build and publish
      if: ${{ steps.ident.outputs.IS_TEST }}
      env:
        TWINE_USERNAME: ${{ secrets.TESTPYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TESTPYPI_PASSWORD }}
        SERVER: ${{ secrets.TESTPYPI_SERVER }}
      run: |
        echo "SECRET: $SERVER"
        if [[ "$TWINE_USERNAME" == "" || "$TWINE_PASSWORD" == "" ]]; then
          echo "::error :: unable to deploy without setting TESTPYPI_USERNAME and TESTPYPI_PASSWORD in the project settings"
          exit 1
        fi
        SERVER=${SERVER:-testpypy}
        echo "::error ::DEPLOY TO ${SERVER}, since this was manually triggered"
        rel-easy publish -r $SERVER

    - name: Build and publish
      if: ${{ steps.ident.outputs.IS_RELEASE }}
      env:
        # TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        SERVER: ${{ secrets.PYPI_SERVER }}
      run: |
        VER=${{ steps.ident.outputs.VERSION }}
        if [[ "$TWINE_USERNAME" == "" || "$TWINE_PASSWORD" == "" ]]; then
          echo "::error :: unable to deploy without setting PYPI_USERNAME and PYPI_PASSWORD in the project settings"
          exit 1
        fi
        SERVER=${SERVER:=pypi}
        echo "TRIGGERED FROM RELEASE PUBLISH TO $SERVER"
        rel-easy publish -r $SERVER
        echo "::warning file=rel-easy-$VER:: Published ${{ steps.ident.outputs.VERSION }} to $SERVER"

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist-${{ steps.ident.outputs.VERSION }}
        path: |
          dist
    - name: Commit Version File
      if: ${{ steps.ident.outputs.IS_RELEASE   }}
      run: |    # this will push the change back up to git
        git config --global user.email "releasy@email.com"
        git config --global user.name "AutoDeploy Script"
        git add releasy/version.py
        git commit -m "Updated Verion to ${{ steps.ident.outputs.VERSION }} And Released build to PyPi"
        git push
    - name: Cleanup
      # run any cleanup needed
      run: |
        echo "All Done..."


