on:
  push:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Identifier'
        required: true
        default: 'a0.0.0v'
jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.7]
    steps: # What do we do?
    # First Checkout our code
    - uses: actions/checkout@v2
    - name: Setup Python ${{ matrix.python-version }}
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |

