name: Lint Package
on:
  push:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Identifier'
        required: true
        default: 'a0.0.0v'
jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.7]
    steps: # What do we do?
    # First Checkout our code
    - uses: actions/checkout@v2
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        pip install flake8
    - name: Lint Critical Errors
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 rel_easy --select=E9,F63,F7,F82 --disable-noqa

    - name: Lint Commit DIFF Only
      run: |
        git diff -U @~..@ | flake8 --diff --tee .lint.DIFF.new.txt

    - name: Lint ALL
      run: |
        flake8 rel_easy --max-line-length=100 --tee --output-file .lint.ALL.new.txt --count

    - name: McCabe Complexity
        run: |
          flake8 rel_easy --max-complexity=6 --max-line-length=100 --select=C901 --tee --output-file .mccabe.ALL.new.txt --count
